meta_product_name: "Fluffy Friend"
meta_title: "Fluffy Friend - A platform to borrow a pet if you can't commit to a pet full-time"
meta_description: "A platform to borrow a pet if you can't commit to a pet full-time"
